### ISSUE TITLE
NullPointerException in Reservoir.java:180

### ISSUE THREAD

**Issue by triveous** [anupcowkur/Reservoir#12] opened 2014-12-02 07:59 UTC
One of my customers is frequently seeing the following issue in a beta version of their app. We've seen over 60+ non-fatals over 3 separate instances affecting 10+ users in a beta test group of around 15

Trace:
```
java.lang.NullPointerException
       at com.anupcowkur.reservoir.Reservoir$GetTask.doInBackground(Reservoir.java:180)
       at com.anupcowkur.reservoir.Reservoir$GetTask.doInBackground(Reservoir.java:163)
       at android.os.AsyncTask$2.call(AsyncTask.java:287)
       at java.util.concurrent.FutureTask.run(FutureTask.java:234)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:856)
```

This happens at multiple locations in the app and has no specific trigger. Reservoir has been initiated in the application object like so:
```java
Reservoir.init(this, 100000);
```

Seems the cache object might be null in Reservoir.java:180, let me know if you need any more information to reproduce the issue

**Comment by dev-mraj** [comment] 2015-02-02 14:55
+1

**Comment by anupcowkur** [comment] 2015-02-03 07:08
closing for now. Will re-open if I can get a reproducible sample.

**Comment by anupcowkur** [comment] 2015-05-26 14:07
Ok. So the issue seems to be that library shows a success message even when the object is not stored due to there not being enough space in the cache to store the object. It should should an error message saying "not enough space in cache!" or something. Re-opening issue now that cause is know.

**Closed** 2015-05-31 07:46 UTC
